### ISSUE TITLE
Change references to branch master to main

### ISSUE THREAD

**Issue by pablogcaldito** [idealista/cookiecutter-ansible-role#23]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filled: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aidealista
    * Checked that there is not already provided the described functionality

### Description
The default branch is now main, so url references to master should be changed

### Steps to Reproduce
N/A

**Expected behavior:**
Updated URLs

**Actual behavior:**
Outdated URLs

**Reproduces how often:**
100%

### Versions
All

### Additional Information
N/A

**Comment by vicsufer** [comment]
I love this one
