### ISSUE TITLE
Redundant script in .travis.yml

### ISSUE THREAD

**Issue by vicsufer** [idealista/cookiecutter-ansible-role#29]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filled: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aidealista
    * Checked that there is not already provided the described functionality

### Description

[Description of the issue]
When creating a role, , travis.yml in the script block it has a line where it sets an environment variable from the same one setup from the jobs block. 

Environment variables setup at the job block are passed before each instruction of the script block, thus this is redundant.

Conflicting line: [`- export MOLECULE_DISTRO=${MOLECULE_DISTRO`](https://github.com/idealista/cookiecutter-ansible-role/blob/develop/%7B%7Bcookiecutter.app_name%7D%7D_role/%7B%25%20raw%20%25%7D.travis.yml%7B%25%20endraw%20%25%7D#L16)

### Steps to Reproduce
N/A

**Expected behavior:** N/A

**Actual behavior:** N/A
**Reproduces how often:** N/A

### Versions
All

### Additional Information
N/A

**Comment by xtianae7** [comment]
solved

**Comment by xtianae7** [comment]
Will be added on the next release.
