### ISSUE TITLE
Current issue template is being deprectated

### ISSUE THREAD

**Issue by vicsufer** [idealista/cookiecutter-ansible-role#30]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filled: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aidealista
    * Checked that there is not already provided the described functionality

### Description

[Description of the issue]
![image](https://user-images.githubusercontent.com/15276132/97148997-554dc900-176c-11eb-9a10-6830f86e4101.png)
[New issue template workflow](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/about-issue-and-pull-request-templates)

Now it seems that we can allow [different type of issues templates](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/configuring-issue-templates-for-your-repository#configuring-the-template-chooser) for bugs, new features or whatever. We should have a look at this.

### Steps to Reproduce

N/A

**Expected behavior:** N/A

**Actual behavior:** N/A

**Reproduces how often:** N/A

### Versions

N/A

### Additional Information

N/A

**Comment by xtianae7** [comment]
Currently, we are only using the same template for every issue, without distinguishing if its a feature request or a bug report.

In this new issue workflow, we can choose if we want to ask for a feature request or report a bug, each with their own template.
We wouldn't be using the feature full potential if we just keep using the same template for both cases.

I think the first thing we should do is properly define the templates.
