### ISSUE TITLE
Take full advantage of Probot

### ISSUE THREAD

**Issue by vicsufer** [idealista/cookiecutter-ansible-role#31]
Idealista currently has a lot of repositories which is harder to maintain as new roles are being generated. We should consider using more features of probot to automate the maintenance of repos as much as possible.
I'm listting some ideas to discuss.

## [Release drafter](https://probot.github.io/apps/release-drafter/)
We can define a template for new releases which will be updated automatically with new merges to master until one maintainer publish it. Ant then the draft process start from the beginning.
Adventages:
- Reduce effort in the release process.
- We can place hints in the draft to review in new releases. Ex: In prom2teams, update setup.py for pypi release.

## [Remove merged branches](https://probot.github.io/apps/delete-merged-branch/)
We should be doing this, but we are humans and make mistakes.
Advantages:
- Avoid slip ups when merging branches.
- Cleaner repository, only active branches in the remote repository.

## [WIP Merge protection](https://probot.github.io/apps/wip/)
This would avoid merging wip pull requests by prefixing the pull request name with "WIP". This may be combined with not testing pull requests that are marked as WIP thus reducing load in travisci, because current configurations tests new commits in branches and PRs thus duplicating tests if PR is open.
Advantages:
- Prevent merges of WIP PR by mistake of other contributor.
- Reduce travis jobs (If an organization has only one concurrent job setup, duplication of testing process can block other repository builds)

## Other
Other features to take into account: https://probot.github.io/apps/

**Comment by dortegau** [comment]
I think it would be nice to do all of them. 

We should investigate if it's possible to add these features to our existing repositories without being a pain in the neck.

**Comment by vicsufer** [comment]
For starters @dortegau , we can try setting default reviewers at the organization level using github teams,
[Auto-assign probot app](https://github.com/kentaro-m/auto-assign#add-github-team-to-single-reviewers-list)

For this we'll need to create the `.github/auto_assign.yml` which may be hard with all our repository (Maybe we can script this), but later on updating reviewers will be only a matter add or remove a member of the team at the organization level.

**Comment by vicsufer** [comment]
It seems that Auto-assign app is not really supporting [not working properly](https://github.com/kentaro-m/auto-assign/issues/102) the integration with github teams. 

Other option is use the CODEOWNERS file, however this will not allow merging with only just one approval unless we set a configuration on the team to enable autoassign which will route a PR review to **only one** member of the team. But this is not our use case where most part of the team review each PR.
![image](https://user-images.githubusercontent.com/15276132/97282868-7af7d280-183f-11eb-90cc-57ee2a7b2407.png)
